# Sponsor and funding links / Sponsor ve finansman bağlantıları

github: https://github.com/sponsors/your-github-username  # GitHub Sponsorluk sayfası
patreon: https://patreon.com/your-patreon-profile          # Patreon profiliniz
open_collective: https://opencollective.com/your-collective # Open Collective topluluğu
ko_fi: https://ko-fi.com/your-ko-fi-profile                 # Ko-fi sayfanız
paypal: https://paypal.me/your-paypal-link                  # PayPal bağış linki
buy_me_a_coffee: https://buymeacoffee.com/your-profile      # Buy Me a Coffee sayfanız
