name: 📦 Dependency Review

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Check for vulnerable dependencies
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------
      # Kodu çek / Checkout the code
      # --------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------------------------------
      # GitHub’ın bağımlılık tarayıcı aksiyonu
      # GitHub’s official dependency review action
      # --------------------------------------------
      - name: GitHub Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high       # yüksek seviyeli zafiyetlerde hata ver / fail on high severity
          # fail-on-scopes: runtime    # sadece runtime bağımlılıkları kontrol et (opsiyonel)
          # license-check: true        # lisans kontrolü de yapmak istersen (opsiyonel)
          # allow-licenses: MIT,Apache-2.0  # sadece bu lisanslara izin ver
